/*
 * File: app/view/Customers.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Customers', {
    extend: 'Ext.form.Panel',

    height: 846,
    width: 1008,
    autoScroll: false,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    bodyPadding: 10,
    title: 'Clients',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'textfield',
                    flex: 0.5,
                    dock: 'top',
                    width: 527,
                    fieldLabel: 'Quick find'
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    title: 'Clients',
                    store: 'clientsStore',
                    viewConfig: {

                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'id',
                            text: 'Id'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'contract_number',
                            text: 'Contract_number'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'registration_number',
                            text: 'Registration_number'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'kmkr_number',
                            text: 'Kmkr_number'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'country',
                            text: 'Country'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'street',
                            text: 'Street'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'state',
                            text: 'State'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'postal_index',
                            text: 'Postal_index'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'contact_person',
                            text: 'Contact_person'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'contact_email',
                            text: 'Contact_email'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'phone_number',
                            text: 'Phone_number'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'fax_number',
                            text: 'Fax_number'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'price_percent',
                            text: 'Price_percent'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'payment_period',
                            text: 'Payment_period'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'reference_number',
                            text: 'Reference_number'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'account_bank',
                            text: 'Account_bank'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'account_number',
                            text: 'Account_number'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'credit',
                            text: 'Credit'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'info_1',
                            text: 'Info_1'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'info_2',
                            text: 'Info_2'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    flex: 5,
                    bodyPadding: 10,
                    title: 'Details',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Name'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Contract number'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Registration number'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'KMKR number'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'County'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Street'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'State'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Postal index'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Contact person'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Contact email'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Phone number'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Fax number'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Price percent'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Payment delay (in days)'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Viite nr.'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Bank'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Account number'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Credit'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            fieldLabel: 'Information'
                        },
                        {
                            xtype: 'button',
                            text: 'Add client'
                        },
                        {
                            xtype: 'button',
                            text: 'Save changes'
                        },
                        {
                            xtype: 'button',
                            text: 'Delete customer'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});