/*
 * File: app/view/userDetails.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.userDetails', {
    extend: 'Ext.form.Panel',

    height: 483,
    width: 768,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    bodyPadding: 10,
    title: 'Users list',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    frame: true,
                    title: 'Users',
                    store: 'usersStore',
                    viewConfig: {

                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'id',
                            text: 'Id'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'type',
                            text: 'Type'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'fullname',
                            text: 'Fullname'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'mobile_number',
                            text: 'Mobile_number'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'phone_number',
                            text: 'Phone_number'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'email',
                            text: 'Email'
                        }
                    ],
                    listeners: {
                        select: {
                            fn: me.onGridpanelSelect,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'form',
                    height: 312,
                    itemId: 'detailsPanel',
                    width: 799,
                    layout: {
                        type: 'auto'
                    },
                    bodyPadding: 10,
                    title: 'Details',
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 224,
                            width: 719,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            title: 'Details',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    itemId: 'id',
                                    width: 736,
                                    readOnly: false,
                                    fieldLabel: 'ID',
                                    decimalPrecision: 0
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'name',
                                    fieldLabel: 'Name',
                                    allowBlank: false,
                                    blankText: 'Name of employee',
                                    minLength: 2
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'fullname',
                                    width: 736,
                                    fieldLabel: 'Fullname'
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'type',
                                    readOnly: false,
                                    fieldLabel: 'User type',
                                    editable: false,
                                    forceSelection: true,
                                    store: 'userTypesStore',
                                    valueField: 'name'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'mobile',
                                    fieldLabel: 'Mobile'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'phone',
                                    fieldLabel: 'Phone'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'email',
                                    fieldLabel: 'Email'
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            text: 'Add user'
                        },
                        {
                            xtype: 'button',
                            text: 'Save changes'
                        },
                        {
                            xtype: 'button',
                            text: 'Delete user'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridpanelSelect: function(selModel, record, index, options) {
        var detailsPanel = this.child('#detailsPanel');

    }

});