/*
 * File: app/model/Clients.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Clients', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'id'
        },
        {
            name: 'name'
        },
        {
            name: 'contract_number'
        },
        {
            name: 'registration_number'
        },
        {
            name: 'kmkr_number'
        },
        {
            name: 'country'
        },
        {
            name: 'street'
        },
        {
            name: 'state'
        },
        {
            name: 'postal_index'
        },
        {
            name: 'contact_person'
        },
        {
            name: 'contact_email'
        },
        {
            name: 'phone_number'
        },
        {
            name: 'fax_number'
        },
        {
            name: 'price_percent'
        },
        {
            name: 'payment_period'
        },
        {
            name: 'reference_number'
        },
        {
            name: 'account_bank'
        },
        {
            name: 'account_number'
        },
        {
            name: 'credit'
        },
        {
            name: 'info_1'
        },
        {
            name: 'info_2'
        }
    ]
});